### ISSUE TITLE
if the list is too long, bash breaks

### ISSUE THREAD

**Issue by kascote** [SidOfc/cani#9]
for example if I do ```cani use shadow```

```
Traceback (most recent call last):
        6: from /home/nelson/.rbenv/versions/2.5.1/bin/cani:23:in `<main>'
        5: from /home/nelson/.rbenv/versions/2.5.1/bin/cani:23:in `load'
        4: from /home/nelson/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cani-0.5.4/exe/cani:6:in `<top (required)>'
        3: from /home/nelson/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cani-0.5.4/lib/cani.rb:35:in `exec!'
        2: from /home/nelson/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cani-0.5.4/lib/cani.rb:124:in `use'
        1: from /home/nelson/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cani-0.5.4/lib/cani/fzf.rb:17:in `pick'
/home/nelson/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cani-0.5.4/lib/cani/fzf.rb:17:in ``': Argument list too long
```

seems the ```rows``` content is too big
https://github.com/SidOfc/cani/blob/master/lib/cani/fzf.rb#L16

may be need to use pipe methods to feed the process ?¿

btw:
bash: GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)
fzf: 0.18.0 (ff95134)

**Comment by SidOfc** [comment]
Hmmn will take a look here as well, thank you for reporting, will share what I figure out :+1:

**Comment by SidOfc** [comment]
I noticed the same issue on my machine while testing things for issue #8. Using `IO.popen` solved the issue, let me know if you experience any other issues.

Thanks again for the reports, A new version has been published :+1:
